// The only place the canvas touches data. Both files are read at build time and
// bundled, so the built site makes no requests of its own.
//
// The map is the repository's example, read in place rather than copied, so there is
// one copy of the invented company. The report is `python3 main.py --json report` over
// that map, regenerated by `make web-data`; buildModel refuses the pair if they disagree.
import map from '../../examples/harbourgate-coffee.json';
import report from './data/report.json';
import { buildModel } from './model.js';

export const MAP = map;
export const REPORT = report;
export const MODEL = buildModel(map, report);
